export const Emoji = [
  { id: 1, name: "Slightly smiling face", symbol: "🙂" },
  { id: 2, name: "Smiling face", symbol: "😀" },
  { id: 3, name: "Laughing with tears", symbol: "😂" },
  { id: 4, name: "Face with mask", symbol: "😷" },
  { id: 5, name: "Angry face", symbol: "😡" },
  { id: 6, name: "Robot", symbol: "🤖" },
  { id: 7, name: "Heart", symbol: "💘" },
  { id: 8, name: "Hand", symbol: "👋" },
  { id: 9, name: "Police", symbol: "👮‍♂️" },
  { id: 10, name: "Thumbs up", symbol: "👍" },
  { id: 11, name: "Thumbs down", symbol: "👎" },
  { id: 12, name: "Fire", symbol: "🔥" },
  { id: 13, name: "Rainbow", symbol: "🌈" },
  { id: 14, name: "Star", symbol: "⭐" },
  { id: 15, name: "Moon", symbol: "🌙" },
  { id: 16, name: "Sun", symbol: "☀️" },
  { id: 17, name: "Cloud", symbol: "☁️" },
  { id: 18, name: "Umbrella", symbol: "☂️" },
  { id: 19, name: "Snowflake", symbol: "❄️" },
  { id: 20, name: "Lightning", symbol: "⚡" },
  { id: 21, name: "Rocket", symbol: "🚀" },
  { id: 22, name: "Camera", symbol: "📷" },
  { id: 23, name: "Book", symbol: "📚" },
  { id: 24, name: "Music note", symbol: "🎵" },
  { id: 25, name: "Basketball", symbol: "🏀" },
  { id: 26, name: "Football", symbol: "⚽" },
  { id: 27, name: "Baseball", symbol: "⚾" },
  { id: 28, name: "Golf", symbol: "⛳" },
  { id: 29, name: "Tennis", symbol: "🎾" },
  { id: 30, name: "Flag", symbol: "🏁" },
  { id: 31, name: "Car", symbol: "🚗" },
  { id: 32, name: "Bicycle", symbol: "🚲" },
  { id: 33, name: "Bus", symbol: "🚌" },
  { id: 34, name: "Train", symbol: "🚆" },
  { id: 35, name: "Ship", symbol: "🚢" },
  { id: 36, name: "Airplane", symbol: "✈️" },
  { id: 37, name: "Computer", symbol: "💻" },
  { id: 38, name: "Phone", symbol: "📱" },
  { id: 39, name: "Clock", symbol: "⏰" },
  { id: 40, name: "Heart eyes", symbol: "😍" },
  { id: 41, name: "Crying face", symbol: "😢" },
  { id: 42, name: "Thinking face", symbol: "🤔" },
  { id: 43, name: "Clapping hands", symbol: "👏" },
  { id: 44, name: "Party popper", symbol: "🎉" },
  { id: 45, name: "Fireworks", symbol: "🎆" },
  { id: 46, name: "Balloon", symbol: "🎈" },
  { id: 47, name: "Cake", symbol: "🍰" },
  { id: 48, name: "Cookie", symbol: "🍪" },
  { id: 49, name: "Ice cream", symbol: "🍨" },
  { id: 50, name: "Coffee", symbol: "☕" },
  { id: 51, name: "Tea", symbol: "🍵" },
  { id: 52, name: "Beer", symbol: "🍺" },
  { id: 53, name: "Wine", symbol: "🍷" },
  { id: 54, name: "Pizza", symbol: "🍕" },
  { id: 55, name: "Hamburger", symbol: "🍔" },
  { id: 56, name: "Hot dog", symbol: "🌭" },
  { id: 57, name: "Taco", symbol: "🌮" },
  { id: 58, name: "Burrito", symbol: "🌯" },
  { id: 59, name: "Spaghetti", symbol: "🍝" },
  { id: 60, name: "Sushi", symbol: "🍣" },
  { id: 61, name: "Curry rice", symbol: "🍛" },
  { id: 62, name: "Popcorn", symbol: "🍿" },
  { id: 63, name: "French fries", symbol: "🍟" },
  { id: 64, name: "Pancakes", symbol: "🥞" },
  { id: 65, name: "Cheese", symbol: "🧀" },
  { id: 66, name: "Chicken leg", symbol: "🍗" },
  { id: 67, name: "Sliced bread", symbol: "🍞" },
  { id: 68, name: "Pineapple", symbol: "🍍" },
  { id: 69, name: "Watermelon", symbol: "🍉" },
  { id: 70, name: "Lemon", symbol: "🍋" },
  { id: 71, name: "Banana", symbol: "🍌" },
  { id: 72, name: "Cherries", symbol: "🍒" },
  { id: 73, name: "Strawberry", symbol: "🍓" },
  { id: 74, name: "Orange", symbol: "🍊" },
  { id: 75, name: "Kiwi fruit", symbol: "🥝" },
  { id: 76, name: "Avocado", symbol: "🥑" },
  { id: 77, name: "Tomato", symbol: "🍅" },
  { id: 78, name: "Eggplant", symbol: "🍆" },
  { id: 79, name: "Carrot", symbol: "🥕" },
  { id: 80, name: "Broccoli", symbol: "🥦" },
  { id: 81, name: "Leafy green", symbol: "🥬" },
  { id: 82, name: "Bell pepper", symbol: "🫑" },
  { id: 83, name: "Garlic", symbol: "🧄" },
  { id: 84, name: "Onion", symbol: "🧅" },
  { id: 85, name: "Mushroom", symbol: "🍄" },
  { id: 86, name: "Cucumber", symbol: "🥒" },
  { id: 87, name: "Peanuts", symbol: "🥜" },
  { id: 88, name: "Baguette bread", symbol: "🥖" },
  { id: 89, name: "Croissant", symbol: "🥐" },
  { id: 90, name: "Cheeseburger", symbol: "🍔" },
  { id: 91, name: "Hot dog with mustard", symbol: "🍟" },
  { id: 92, name: "Slice of pizza", symbol: "🍕" },
  { id: 93, name: "Taco with guacamole", symbol: "🥑" },
  { id: 94, name: "Sushi roll", symbol: "🍙" },
  { id: 95, name: "Chocolate bar", symbol: "🍫" },
  { id: 96, name: "Ice cream cone", symbol: "🍦" },
  { id: 97, name: "Doughnut", symbol: "🍩" },
  { id: 98, name: "Lollipop", symbol: "🍭" },
  { id: 99, name: "Cupcake", symbol: "🧁" },
  { id: 100, name: "Birthday cake", symbol: "🎂" },
];
